name: macos-build
on: 
  push:
    # branches:
    #   - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create output dir
        run: mkdir out
        
      - name: Configure the project.
        run: cmake $GITHUB_WORKSPACE
        working-directory: out

      - name: Build the project.
        run: cmake --build out --config Release

      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: out/Release