name: ubuntu-build
on: 
  push:
    # branches:
    #   - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: "export"

      - run: "sudo apt install -y build-essential cmake curl zip unzip tar libgl-dev"
  
      - name: Create output dir
        run: mkdir build
        
      - name: Configure the project.
        run: cmake $GITHUB_WORKSPACE -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=./out
        working-directory: build

      - name: Build the project.
        run: cmake --build $GITHUB_WORKSPACE/build --config Release

      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu
          path: $GITHUB_WORKSPACE/build/out
